import type { AppState } from './types';
import { DEFAULT_ABILITIES } from './data/abilityTables';

export const DEFAULT_STATE: AppState = {
  version: 19,
  language: 'ja',
  activeTab: 'graph',
  targets: [
    {
      id: 'target-1',
      recipeId: 'charcoal_powder_from_charcoal',
      outputItemId: 'charcoal_powder',
      mode: 'rate',
      value: 30,
    },
  ],
  settings: {
    machineRounding: 'none',
  quantityRoundingStep: '0.01',
    defaultSurplusPolicy: 'reuse',
    graphDetailLevel: 'normal',
    showSurplus: true,
    showDiscardedByproducts: true,
    showCompleted: true,
    fuel: {
      enabled: true,
      fuelItemId: 'charcoal_powder',
      fuelSourceMode: 'craft',
      crucibleVariant: 'crucible',
      crucibleOverheadHeatPerSec: 0.4,
      otherOverheadHeatPerSec: 1,
      maxIterations: 8,
    },
    fertilizer: {
      enabled: false,
      fertilizerItemId: 'basic_fertilizer',
      fertilizerSourceMode: 'craft',
      nurseryNutrientsPerSec: 12,
      maxIterations: 4,
    },
  },
  abilities: DEFAULT_ABILITIES,
  recipePreferences: {
  coke: 'coke',
  emerald: 'emerald',
  sapphire: 'sapphire',
  ruby: 'ruby',
  adamant: 'adamant',
  obsidian: 'obsidian_and_volcanic_ash',
  iron_sand: 'iron_sand',
  shattered_crystal: 'shattered_crystal',
  salt: 'salt_and_sand_2',
  sand: 'sand',
  copper_powder: 'copper_powder_and_impure_copper_powder',
  gold_dust: 'gold_dust',
  impure_gold_dust: 'impure_gold_dust',
},
  surplusPolicies: {},
  itemSourceModes: {},
  completedGraphNodeIds: {},
  nodeNotes: {},
};
